### ISSUE TITLE
Ability to open .mpp files (binary)

### ISSUE THREAD

**Issue by rpbouman** [rpbouman/open-msp-viewer#10]
Currently the open-msp-viewer can open only XML files (see http://msdn.microsoft.com/en-us/library/bb968652(v=office.12).aspx), regardless of the MS Project version. 

The native format preferred by the MS Project software itself is the binary .mpp format. This issue is to
1) see how many users would like to see the open-msp-viewer handling .mpp files directly 
2) to gather contributions (be it effort, information, money) towards realizing such a feature.

Microsoft has published the specification for a number of its binary office file formates (see http://msdn.microsoft.com/en-us/library/office/cc313105(v=office.12).aspx). Sadly, the .mpp file format is not among these, nor does there seem any plan to publish this )(see http://social.msdn.microsoft.com/Forums/en-US/fd590f09-919f-497d-a6c7-a7fc05963886/mpp-format?forum=os_binaryfile). A specification of the .mpp format would be a significant contribution required from the community to make this feature happen.

There is currently one open source library that I know of that can read .mpp files called mpxj (see http://mpxj.sourceforge.net/). This java library itself relies on apache's poi library (http://poi.apache.org/). In principle, the source code for these projects could be analyzed to prepare a specification of the .mpp file format.

So please leave a comment to explain why you would need this feature, and/or if you would like to contribute towards realizing it.

**Comment by s7726** [comment]
https://kaitai.io/
https://ide.kaitai.io/
```yaml
meta:
  id: compobj
  endian: le
  encoding: ASCII
seq:
  - id: unk_skip
    size: 28
  - id: av_size
    type: u4
  - id: app_version
    type: str
    size: av_size
  - id: ff_size
    type: u4
  - id: file_format
    type: str
    size: ff_size
  - id: aid_size
    type: u4
  - id: app_id
    type: str
    size: aid_size
```
Turns into:
```json
{
  "unkSkip": [1, 0, 254, 255, 3, 10, 0, 0, 255, 255, 255, 255, 58, 143, 183, 116, 200, 200, 209, 17, 190, 17, 0, 192, 79, 182, 250, 241],
  "avSize": 23,
  "appVersion": "Microsoft.Project 14.0\u0000",
  "ffSize": 16,
  "fileFormat": "MSProject.MPP14\u0000",
  "aidSize": 20,
  "appId": "MSProject.Project.9\u0000"
}
```

Borrowing heavily from the work done by [mpxj](https://github.com/joniles/mpxj) Using kaitai the format can be converted to various languages, including javascript.

mpp file is a zip containing various other files. If we can get all of those parsed we should have a start. There will definitely be some interdependence that will need to be figured out.

Source of sample mpp files (Project 2010): https://resources.oreilly.com/examples/9780735626959-files/
